'use client';
import { useState } from 'react';

const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
type Msg = {role:string; content:string};
export default function Home() {
  const [token,setToken]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState('');
  const [messages,setMessages]=useState<Msg[]>([]); const [goal,setGoal]=useState(''); const [fileId,setFileId]=useState<number|undefined>();
  const [status,setStatus]=useState(''); const [plan,setPlan]=useState<any[]>([]);
  async function auth(path:string) { const r=await fetch(`${API}/auth/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})}); const d=await r.json(); if(!r.ok){setStatus(d.detail||'Authentication failed');return;} setToken(d.access_token);setStatus('Signed in'); }
  async function upload(f?:File) { if(!f)return; const body=new FormData();body.append('file',f); const r=await fetch(`${API}/files/upload`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body});const d=await r.json();if(r.ok){setFileId(d.id);setStatus(`Attached ${d.filename}`)}else setStatus(d.detail||'Upload failed'); }
  async function send() { if(!goal.trim()||!token)return; const prompt=goal;setMessages(m=>[...m,{role:'user',content:prompt}]);setGoal('');setStatus('Planning and executing');try{const r=await fetch(`${API}/agent/run`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({goal:prompt,file_id:fileId})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Request failed');setPlan(d.plan||[]);setMessages(m=>[...m,{role:'assistant',content:d.result}]);setStatus(`Task ${d.task_id}: ${d.status}`)}catch(e){setStatus(String(e));} }
  return <main><header><div className="brand">AURA<span>Autonomous Unified Reasoning Agent</span></div><div className="auth">{!token?<><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Password (8+ chars)" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={()=>auth('register')}>Create account</button><button className="secondary" onClick={()=>auth('login')}>Sign in</button></>:<button className="secondary" onClick={()=>{setToken('');setStatus('Signed out')}}>Sign out</button>}</div></header>
  <div className="shell"><section className="chat"><div className="intro"><p className="eyebrow">YOUR AI WORKSPACE</p><h1>Turn a goal into<br/><em>verified work.</em></h1><p>Plan tasks, analyze your files, and see what AURA actually completed.</p></div><div className="messages">{messages.map((m,i)=><article key={i} className={m.role}><b>{m.role==='user'?'You':'AURA'}</b><p>{m.content}</p></article>)}</div><div className="composer"><textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Describe a task, or attach a CSV to analyze…"/><div className="controls"><label className="file">＋ Attach file<input type="file" accept=".txt,.md,.csv,.json,.xlsx" onChange={e=>upload(e.target.files?.[0])}/></label><span>{status}</span><button onClick={send} disabled={!token}>Run task →</button></div></div></section><aside><div className="panel"><p className="eyebrow">TASK PLAN</p><h2>Activity</h2>{plan.length?plan.map((p:any)=><div className="step" key={p.id}><span>{p.status==='COMPLETED'?'✓':p.status==='WAITING'?'!':'○'}</span><div><b>{p.name}</b><small>{p.agent}{p.note?` · ${p.note}`:''}</small></div></div>):<p className="muted">Task steps appear here when you run a request.</p>}</div><div className="panel note"><p className="eyebrow">HONEST BY DESIGN</p><p>AURA labels unavailable integrations and reports failures instead of inventing results.</p></div></aside></div></main>
}
